{"name": "test_login_with_password", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\n    at UIA2Proxy.command (/Users/lekhraj/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.doFindElementOrEls (/Users/lekhraj/.appium/node_modules/appium-uiautomator2-driver/lib/commands/find.js:40:5)\n    at doFind (/Users/lekhraj/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:47:17)\n    at wrappedCondFn (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/timeout.ts:137:14)\n    at spin (/Users/lekhraj/node_modules/@appium/base-driver/node_modules/asyncbox/lib/asyncbox.js:219:20)\n    at waitForCondition (/Users/lekhraj/node_modules/@appium/base-driver/node_modules/asyncbox/lib/asyncbox.js:236:10)\n    at AndroidUiautomator2Driver.implicitWaitForCondition (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/timeout.ts:139:12)\n    at AndroidUiautomator2Driver.findElOrEls (/Users/lekhraj/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:70:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)", "trace": "self = <Testcases.test_E2E.TestEmbibeApp object at 0x102957700>\n\n    @pytest.mark.usefixtures(\"appiumdriver\", \"log_on_failure\")\n    def test_login_with_password(self):\n>       self._login_with_password()\n\nTestcases/test_E2E.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestcases/test_E2E.py:18: in _login_with_password\n    lp.signinusingpassword()\nPages/landingPages.py:31: in signinusingpassword\n    self.driver.find_element(*landingpages.location_continue_btn).click()\n../../Library/Python/3.10/lib/python/site-packages/appium/webdriver/webdriver.py:382: in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n../../Library/Python/3.10/lib/python/site-packages/selenium/webdriver/remote/webdriver.py:380: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x1029aca00>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"An unknown server-side error occurred while pro...tomator2Driver.findElement (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        if isinstance(payload, dict):\n            payload_dict = payload\n        else:\n            try:\n                payload_dict = json.loads(payload)\n            except (json.JSONDecodeError, TypeError):\n                return\n            if not isinstance(payload_dict, dict):\n                return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\nE       Stacktrace:\nE       UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\nE           at UIA2Proxy.command (/Users/lekhraj/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)\nE           at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE           at AndroidUiautomator2Driver.doFindElementOrEls (/Users/lekhraj/.appium/node_modules/appium-uiautomator2-driver/lib/commands/find.js:40:5)\nE           at doFind (/Users/lekhraj/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:47:17)\nE           at wrappedCondFn (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/timeout.ts:137:14)\nE           at spin (/Users/lekhraj/node_modules/@appium/base-driver/node_modules/asyncbox/lib/asyncbox.js:219:20)\nE           at waitForCondition (/Users/lekhraj/node_modules/@appium/base-driver/node_modules/asyncbox/lib/asyncbox.js:236:10)\nE           at AndroidUiautomator2Driver.implicitWaitForCondition (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/timeout.ts:139:12)\nE           at AndroidUiautomator2Driver.findElOrEls (/Users/lekhraj/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:70:5)\nE           at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\nE           at AndroidUiautomator2Driver.findElement (/Users/lekhraj/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n\n../../Library/Python/3.10/lib/python/site-packages/appium/webdriver/errorhandler.py:125: WebDriverException"}, "start": 1732374457169, "stop": 1732374457224, "uuid": "9eb48139-163b-4d98-890c-3ba5aa445c9a", "historyId": "91161c11966ce952399f5a2bb7073cce", "testCaseId": "91161c11966ce952399f5a2bb7073cce", "fullName": "Testcases.test_E2E.TestEmbibeApp#test_login_with_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('appiumdriver', 'log_on_failure')"}, {"name": "parentSuite", "value": "Testcases"}, {"name": "suite", "value": "test_E2E"}, {"name": "subSuite", "value": "TestEmbibeApp"}, {"name": "host", "value": "EBL-C02H385BQ6L4.local"}, {"name": "thread", "value": "6402-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcases.test_E2E"}]}